workflows:
  android-release:
    name: Android Release Build

    max_build_duration: 60

    environment:
      java: 17

    scripts:
      - chmod +x gradlew
      - ./gradlew clean
      - ./gradlew assembleRelease

    artifacts:
      - app/build/outputs/apk/**/*.apk
      - app/build/outputs/bundle/**/*.aab
      - app/build/reports/**/*

    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper
