package com.example.ui

object Localization {

    private val englishStrings = mapOf(
        "app_name" to "Don't Touch My Phone",
        "tagline" to "Protect your device with smart alarms",
        "splash_loading" to "Securing your device...",
        "next" to "Next",
        "skip" to "Skip",
        "get_started" to "Get Started",
        "onboarding_title_1" to "Don't Touch My Phone",
        "onboarding_desc_1" to "Triggers a loud siren alarm immediately if someone picks up or moves your phone from the table.",
        "onboarding_title_2" to "Intruder Alert & Selfie",
        "onboarding_desc_2" to "Snaps a silent photo using the front camera when someone tries to browse or unlock your phone.",
        "onboarding_title_3" to "Pocket & Charger Safety",
        "onboarding_desc_3" to "Receive alerts when the charger is disconnected or when the phone is pulled out of your pocket.",
        "permissions_title" to "Setup Permissions",
        "permissions_desc" to "To work reliably, the app requires the following system permissions. Please enable them.",
        "perm_camera" to "Camera Access",
        "perm_camera_desc" to "Required to capture silent selfies of intruders.",
        "perm_notification" to "Notifications",
        "perm_notification_desc" to "Allows the security service to run in the background safely.",
        "perm_audio" to "Microphone",
        "perm_audio_desc" to "Required for Clap & Whistle detection.",
        "grant" to "Grant",
        "granted" to "Granted",
        "continue_btn" to "Continue",
        "activate" to "ACTIVATE",
        "deactivate" to "DEACTIVATE",
        "status_armed" to "Security System is ACTIVE",
        "status_disarmed" to "Tap below to arm your phone",
        "select_mode" to "Select Alarm Mode",
        "mode_dont_touch" to "Don't Touch Mode",
        "mode_dont_touch_desc" to "Triggers if your device is lifted or moved.",
        "mode_motion" to "Motion Alarm",
        "mode_motion_desc" to "Detects sharp movements or shaking.",
        "mode_pocket" to "Pocket Mode",
        "mode_pocket_desc" to "Alerts if pulled out of pocket/bag.",
        "mode_charging" to "Charging Alarm",
        "mode_charging_desc" to "Alerts if charger is unplugged.",
        "mode_who_touch" to "Who Touched",
        "mode_who_touch_desc" to "Captures front selfie on any movement.",
        "mode_clap_whistle" to "Clap/Whistle",
        "mode_clap_whistle_desc" to "Sounds alarm on claps or whistles.",
        "setup_pin_title" to "Setup Security PIN",
        "setup_pin_desc" to "Create a 4-digit PIN to deactivate the alarm.",
        "enter_pin" to "Enter Security PIN",
        "pin_incorrect" to "Incorrect PIN! Try again.",
        "pin_set_success" to "PIN configured successfully!",
        "confirm_pin" to "Confirm Security PIN",
        "tab_home" to "Home",
        "tab_modes" to "Modes",
        "tab_photos" to "Photos",
        "tab_history" to "History",
        "tab_sounds" to "Sounds",
        "tab_settings" to "Settings",
        "alarm_triggered" to "ALARM TRIGGERED!",
        "breach_detected" to "Breach Detected in",
        "enter_pin_deactivate" to "Enter PIN to Deactivate Siren",
        "intruder_captured" to "Intruder Selfie Captured!",
        "no_photos" to "No intruder selfies captured yet.",
        "photos_desc" to "Silent front-camera photos of unauthorized users will appear here.",
        "delete" to "Delete",
        "clear_all" to "Clear All",
        "no_history" to "Security logs are empty.",
        "history_desc" to "Past alarms, triggers, and intruder records are listed below.",
        "export_logs" to "Export Logs",
        "sound_select_title" to "Configure Alarm Siren",
        "preview" to "Preview",
        "sensitivity" to "Alarm Sensitivity",
        "flash_alert" to "Flashlight Strobe",
        "vibrate" to "Vibration Alarm",
        "countdown" to "Start Countdown",
        "seconds" to "seconds",
        "dark_mode" to "Dark Mode",
        "language" to "App Language",
        "dev_profile" to "Developer Profile",
        "dev_name" to "Prince AR Abdur Rahman",
        "dev_title" to "Independent App Developer",
        "dev_desc" to "Passionate about building modern Android applications, productivity tools, AI-powered experiences, media players, educational apps, and next-generation digital products.",
        "contact_me" to "Contact Developer",
        "whatsapp" to "WhatsApp",
        "facebook" to "Facebook",
        "instagram" to "Instagram",
        "company" to "About NexVora Lab's Ofc",
        "company_desc" to "NexVora Lab's Ofc focuses on creating innovative Android applications designed to improve productivity, entertainment, learning, and digital experiences.",
        "company_mission" to "Mission: Build fast, beautiful, privacy-friendly, and user-focused applications accessible to everyone.",
        "credits" to "Credits & Version",
        "version" to "Version 1.0.0",
        "rights" to "© 2026 NexVora Lab's Ofc. All Rights Reserved.",
        "about_company" to "About Company"
    )

    private val banglaStrings = mapOf(
        "app_name" to "ডন্ট টাচ মাই ফোন",
        "tagline" to "স্মার্ট অ্যালার্ম দিয়ে ফোন সুরক্ষিত রাখুন",
        "splash_loading" to "ডিভাইস সুরক্ষিত করা হচ্ছে...",
        "next" to "পরবর্তী",
        "skip" to "এড়িয়ে যান",
        "get_started" to "শুরু করুন",
        "onboarding_title_1" to "স্পর্শ করবেন না মোড",
        "onboarding_desc_1" to "কেউ আপনার ফোন টেবিল থেকে তুললে বা সরালে সাথে সাথে জোরে সাইরেন বেজে উঠবে।",
        "onboarding_title_2" to "অনুপ্রবেশকারী সেলফি অ্যালার্ট",
        "onboarding_desc_2" to "কেউ আপনার ফোন আনলক করার চেষ্টা করলে সামনের ক্যামেরা দিয়ে গোপনে ছবি তুলে রাখবে।",
        "onboarding_title_3" to "পকেট ও চার্জার নিরাপত্তা",
        "onboarding_desc_3" to "চার্জার খুলে ফেললে অথবা পকেট থেকে ফোন বের করার চেষ্টা করলে সাথে সাথে অ্যালার্ট পান।",
        "permissions_title" to "অনুমতি সেটআপ করুন",
        "permissions_desc" to "অ্যাপটি সঠিকভাবে কাজ করার জন্য নিচের সিস্টেম পারমিশনগুলো প্রয়োজন। অনুগ্রহ করে অন করুন।",
        "perm_camera" to "ক্যামেরা অ্যাক্সেস",
        "perm_camera_desc" to "অনুপ্রবেশকারীর ছবি তোলার জন্য এটি প্রয়োজন।",
        "perm_notification" to "নোটিফিকেশন",
        "perm_notification_desc" to "ব্যাকগ্রাউন্ডে সিকিউরিটি সার্ভিস চালু রাখার অনুমতি দেয়।",
        "perm_audio" to "মাইক্রোফোন",
        "perm_audio_desc" to "হাততালি ও শিস শনাক্তকরণের জন্য এটি প্রয়োজন।",
        "grant" to "অনুমতি দিন",
        "granted" to "অনুমতি দেওয়া হয়েছে",
        "continue_btn" to "চালিয়ে যান",
        "activate" to "সক্রিয় করুন",
        "deactivate" to "নিষ্ক্রিয় করুন",
        "status_armed" to "সিকিউরিটি সিস্টেম সক্রিয় আছে",
        "status_disarmed" to "সক্রিয় করতে নিচে ট্যাপ করুন",
        "select_mode" to "অ্যালার্ম মোড নির্বাচন করুন",
        "mode_dont_touch" to "স্পর্শ করবেন না মোড",
        "mode_dont_touch_desc" to "ডিভাইস নাড়ালে অ্যালার্ম বাজবে।",
        "mode_motion" to "মোশন অ্যালার্ম",
        "mode_motion_desc" to "ফোনে তীব্র ঝাঁকুনি শনাক্ত করে।",
        "mode_pocket" to "পকেট মোড",
        "mode_pocket_desc" to "পকেট বা ব্যাগ থেকে বের করলে অ্যালার্ট দেয়।",
        "mode_charging" to "চার্জিং অ্যালার্ম",
        "mode_charging_desc" to "চার্জার খুলে ফেললে অ্যালার্ট বেজে উঠবে।",
        "mode_who_touch" to "কে ফোন ধরেছে",
        "mode_who_touch_desc" to "কোনো নড়াচড়া হলেই সামনের সেলফি তোলে।",
        "mode_clap_whistle" to "হাততালি/শিস",
        "mode_clap_whistle_desc" to "হাততালি বা শিসের আওয়াজে অ্যালার্ম বাজে।",
        "setup_pin_title" to "সিকিউরিটি পিন সেটআপ",
        "setup_pin_desc" to "অ্যালার্ম বন্ধ করার জন্য একটি ৪-ডিজিট পিন তৈরি করুন।",
        "enter_pin" to "সিকিউরিটি পিন দিন",
        "pin_incorrect" to "ভুল পিন! আবার চেষ্টা করুন।",
        "pin_set_success" to "পিন সফলভাবে সেট করা হয়েছে!",
        "confirm_pin" to "পিন নিশ্চিত করুন",
        "tab_home" to "হোম",
        "tab_modes" to "মোড সমূহ",
        "tab_photos" to "ছবি",
        "tab_history" to "ইতিহাস",
        "tab_sounds" to "সাউন্ড",
        "tab_settings" to "সেটিংস",
        "alarm_triggered" to "অ্যালার্ম বেজে উঠেছে!",
        "breach_detected" to "লঙ্ঘন সনাক্ত হয়েছে",
        "enter_pin_deactivate" to "সাইরেন বন্ধ করতে পিন দিন",
        "intruder_captured" to "অনুপ্রবেশকারীর ছবি তোলা হয়েছে!",
        "no_photos" to "এখনো কোনো অনুপ্রবেশকারীর ছবি নেই।",
        "photos_desc" to "অননুমোদিত ব্যবহারকারীদের তোলা ছবি এখানে প্রদর্শিত হবে।",
        "delete" to "মুছে ফেলুন",
        "clear_all" to "সব মুছুন",
        "no_history" to "নিরাপত্তা ইতিহাস খালি রয়েছে।",
        "history_desc" to "অতীতের অ্যালার্ম এবং অনুপ্রবেশের রেকর্ড এখানে দেখতে পাবেন।",
        "export_logs" to "লগ এক্সপোর্ট",
        "sound_select_title" to "অ্যালার্ম সাইরেন পরিবর্তন করুন",
        "preview" to "শুনুন",
        "sensitivity" to "অ্যালার্ম সংবেদনশীলতা",
        "flash_alert" to "ফ্ল্যাশলাইট স্ট্রব",
        "vibrate" to "ভাইব্রেশন অ্যালার্ম",
        "countdown" to "কাউন্টডাউন শুরু",
        "seconds" to "সেকেন্ড",
        "dark_mode" to "ডার্ক মোড",
        "language" to "অ্যাপের ভাষা",
        "dev_profile" to "ডেভেলপার প্রোফাইল",
        "dev_name" to "প্রিন্স এ আর আবদুর রহমান",
        "dev_title" to "স্বতন্ত্র অ্যাপ ডেভেলপার",
        "dev_desc" to "আধুনিক অ্যান্ড্রয়েড অ্যাপ্লিকেশন, প্রোডাক্টিভিটি টুলস, এআই-চালিত অভিজ্ঞতা, মিডিয়া প্লেয়ার, শিক্ষামূলক অ্যাপ এবং পরবর্তী প্রজন্মের ডিজিটাল পণ্য তৈরিতে আগ্রহী ও নিবেদিত।",
        "contact_me" to "যোগাযোগ করুন",
        "whatsapp" to "হোয়াটসঅ্যাপ",
        "facebook" to "ফেসবুক",
        "instagram" to "ইনস্টাগ্রাম",
        "company" to "নেক্সভোরা ল্যাব সম্পর্কে",
        "company_desc" to "নেক্সভোরা ল্যাব মূলত প্রোডাক্টিভিটি, বিনোদন, শিক্ষা ও উন্নত ডিজিটাল অভিজ্ঞতার জন্য আধুনিক অ্যান্ড্রয়েড অ্যাপ্লিকেশন তৈরিতে কাজ করে।",
        "company_mission" to "লক্ষ্য: সবার জন্য দ্রুত, সুন্দর, গোপনীয়তা-বান্ধব ও ব্যবহারকারী-কেন্দ্রিক অ্যাপ্লিকেশন তৈরি করা।",
        "credits" to "ক্রেডিট ও সংস্করণ",
        "version" to "সংস্করণ ১.০.০",
        "rights" to "© ২০২৬ নেক্সভোরা ল্যাব। সর্বস্বত্ব সংরক্ষিত।",
        "about_company" to "কোম্পানি সম্পর্কে"
    )

    fun getString(key: String, language: String): String {
        return if (language == "bn") {
            banglaStrings[key] ?: englishStrings[key] ?: key
        } else {
            englishStrings[key] ?: key
        }
    }
}
